# Generated by Django 4.0.6 on 2022-07-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
