# Generated by Django 4.0.6 on 2022-09-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderhistorymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
