# Generated by Django 4.0.6 on 2022-09-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderhistorymodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
